version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: marcosaurios/martian-robots
    docker:
      - image: circleci/buildpack-deps:stretch
  node:
    docker:
      - image: circleci/node:12-browsers
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build-node:
    executor: node
    steps:
      - checkout
      - run: npm install --only-prod=true
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  build-docker:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:prod .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME
workflows:
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only: dev
      - build-node:
          requires:
            - test
          filters:
            branches:
              only: dev
      - build-docker:
          requires:
            - build-node
          filters:
            branches:
              only: dev
      - publish-latest:
          requires:
            - build-docker
          filters:
            branches:
              only: dev
